language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

before_install:
- mkdir ~/.R
- npm install libgdal-dev gdal-bin libproj-dev
#- npm install netlify-cli -g

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

#deploy:
#  provider: script
#  script: bash scripts/deploy.sh
#  skip_cleanup: true
